name: empirical_dope
description: A KISS empirical ballistic calculator that learns from real DOPE.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  intl: ^0.18.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Dart test runner for non-Flutter unit tests.
  test: ^1.25.2
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/shotview_mv_series.csv
    - assets/geoballistics_export.csv
    - assets/ab_quantum_export.csv